// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "bug": Application Controllers
//
// Command:
// $ goagen
// --design=github.com/Ashtonian/goa-bug-repro/design
// --out=$(GOPATH)/src/github.com/Ashtonian/goa-bug-repro
// --version=v1.3.1

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

// initService sets up the service encoders, decoders and mux.
func initService(service *goa.Service) {
	// Setup encoders and decoders
	service.Encoder.Register(goa.NewJSONEncoder, "application/json")
	service.Encoder.Register(goa.NewGobEncoder, "application/gob", "application/x-gob")
	service.Encoder.Register(goa.NewXMLEncoder, "application/xml")
	service.Decoder.Register(goa.NewJSONDecoder, "application/json")
	service.Decoder.Register(goa.NewGobDecoder, "application/gob", "application/x-gob")
	service.Decoder.Register(goa.NewXMLDecoder, "application/xml")

	// Setup default encoder and decoder
	service.Encoder.Register(goa.NewJSONEncoder, "*/*")
	service.Decoder.Register(goa.NewJSONDecoder, "*/*")
}

// BugController is the controller interface for the Bug actions.
type BugController interface {
	goa.Muxer
	Example(*ExampleBugContext) error
}

// MountBugController "mounts" a Bug resource controller on the given service.
func MountBugController(service *goa.Service, ctrl BugController) {
	initService(service)
	var h goa.Handler

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewExampleBugContext(ctx, req, service)
		if err != nil {
			return err
		}
		// Build the payload
		if rawPayload := goa.ContextRequest(ctx).Payload; rawPayload != nil {
			rctx.Payload = rawPayload.(*ExampleRequest)
		} else {
			return goa.MissingPayloadError()
		}
		return ctrl.Example(rctx)
	}
	service.Mux.Handle("POST", "/api/bug", ctrl.MuxHandler("example", h, unmarshalExampleBugPayload))
	service.LogInfo("mount", "ctrl", "Bug", "action", "Example", "route", "POST /api/bug")
}

// unmarshalExampleBugPayload unmarshals the request body into the context request data Payload field.
func unmarshalExampleBugPayload(ctx context.Context, service *goa.Service, req *http.Request) error {
	payload := &exampleRequest{}
	if err := service.DecodeRequest(req, payload); err != nil {
		return err
	}
	goa.ContextRequest(ctx).Payload = payload.Publicize()
	return nil
}
