// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "bug": Application Contexts
//
// Command:
// $ goagen
// --design=github.com/Ashtonian/goa-bug-repro/design
// --out=$(GOPATH)/src/github.com/Ashtonian/goa-bug-repro
// --version=v1.3.1

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

// ExampleBugContext provides the bug example action context.
type ExampleBugContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	Payload *ExampleRequest
}

// NewExampleBugContext parses the incoming request URL and body, performs validations and creates the
// context used by the bug controller example action.
func NewExampleBugContext(ctx context.Context, r *http.Request, service *goa.Service) (*ExampleBugContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := ExampleBugContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *ExampleBugContext) OK(resp []byte) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "text/plain")
	}
	ctx.ResponseData.WriteHeader(200)
	_, err := ctx.ResponseData.Write(resp)
	return err
}
