// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "bug": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/Ashtonian/goa-bug-repro/design
// --out=$(GOPATH)/src/github.com/Ashtonian/goa-bug-repro
// --version=v1.3.1

package app
