// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "bug": Application User Types
//
// Command:
// $ goagen
// --design=github.com/Ashtonian/goa-bug-repro/design
// --out=$(GOPATH)/src/github.com/Ashtonian/goa-bug-repro
// --version=v1.3.1

package app

import (
	"github.com/goadesign/goa"
	"time"
)

// exampleRequest user type.
type exampleRequest struct {
	EndTime   *time.Time `form:"endTime,omitempty" json:"endTime,omitempty" xml:"endTime,omitempty"`
	ID        *int       `form:"id,omitempty" json:"id,omitempty" xml:"id,omitempty"`
	StartTime *time.Time `form:"startTime,omitempty" json:"startTime,omitempty" xml:"startTime,omitempty"`
}

// Validate validates the exampleRequest type instance.
func (ut *exampleRequest) Validate() (err error) {
	if ut.ID == nil {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`request`, "id"))
	}
	return
}

// Publicize creates ExampleRequest from exampleRequest
func (ut *exampleRequest) Publicize() *ExampleRequest {
	var pub ExampleRequest
	if ut.EndTime != nil {
		pub.EndTime = ut.EndTime
	}
	if ut.ID != nil {
		pub.ID = *ut.ID
	}
	if ut.StartTime != nil {
		pub.StartTime = ut.StartTime
	}
	return &pub
}

// ExampleRequest user type.
type ExampleRequest struct {
	EndTime   *time.Time `form:"endTime,omitempty" json:"endTime,omitempty" xml:"endTime,omitempty"`
	ID        int        `form:"id" json:"id" xml:"id"`
	StartTime *time.Time `form:"startTime,omitempty" json:"startTime,omitempty" xml:"startTime,omitempty"`
}
